export const COMPETITIONS = [
            {
                id: "premier",
                name: "Premier League",
                emoji: "🇬🇧",
                format: "league",
                teamCount: 20,
                rounds: 38,
                teams: [
                    "Arsenal", "Aston Villa", "Bournemouth", "Brentford", "Brighton", "Chelsea",
                    "Crystal Palace", "Everton", "Fulham", "Ipswich Town", "Leicester City", "Liverpool",
                    "Man City", "Man United", "Newcastle", "Nottingham", "Southampton", "Tottenham",
                    "West Ham", "Wolves",
                ],
                positionStyles: {
                    1: { bg: "bg-yellow-900/40", border: "border-yellow-500/60", icon: "🏆", label: "Champion" },
                    "2-5": { bg: "bg-blue-900/40", border: "border-blue-500/60", icon: "🇪🇺", label: "Champions League" },
                    6: { bg: "bg-orange-900/40", border: "border-orange-500/60", icon: "🇪🇺", label: "Europa League" },
                    7: { bg: "bg-green-900/40", border: "border-green-500/60", icon: "🇪🇺", label: "Conference League" },
                    "18-20": { bg: "bg-red-900/40", border: "border-red-500/60", icon: "⬇️", label: "Relegated" },
                },
            },
      {
        id: "scottish",
        name: "Scottish Premiership",
        emoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
        format: "league",
        teamCount: 12,
        rounds: 22,
        teams: [
          "Aberdeen",
          "Celtic",
          "Dundee",
          "Dundee United",
          "Hearts",
          "Hibernian",
          "Kilmarnock",
          "Livingston",
          "Motherwell",
          "Rangers",
          "Ross County",
          "St. Mirren",
        ],
        positionStyles: {
          1: {
            bg: "bg-yellow-900/40",
            border: "border-yellow-500/60",
            icon: "🏆",
            label: "Champion",
          },
          2: {
            bg: "bg-blue-900/40",
            border: "border-blue-500/60",
            icon: "🇪🇺",
            label: "Champions League Qual.",
          },
          "3-4": {
            bg: "bg-orange-900/40",
            border: "border-orange-500/60",
            icon: "🇪🇺",
            label: "Europa/Conference League",
          },
          11: {
            bg: "bg-red-900/40",
            border: "border-red-500/60",
            icon: "🔄",
            label: "Playoff (Relegation)",
          },
          12: {
            bg: "bg-red-900/40",
            border: "border-red-500/60",
            icon: "⬇️",
            label: "Relegated",
          },
        },
      },
      {
        id: "championship",
        name: "EFL Championship",
        emoji: "🇬🇧",
        format: "league",
        teamCount: 24,
        rounds: 46,
        teams: [
          "Birmingham City",
          "Blackburn Rovers",
          "Bristol City",
          "Charlton Athletic",
          "Coventry City",
          "Derby County",
          "Hull City",
          "Ipswich Town",
          "Leicester City",
          "Middlesbrough",
          "Millwall",
          "Norwich City",
          "Oxford United",
          "Portsmouth",
          "Preston North End",
          "Queens Park Rangers",
          "Sheffield United",
          "Sheffield Wednesday",
          "Southampton",
          "Stoke City",
          "Swansea City",
          "Watford",
          "West Bromwich Albion",
          "Wrexham",
        ],
        positionStyles: {
          "1-2": {
            bg: "bg-yellow-900/40",
            border: "border-yellow-500/60",
            icon: "⬆️",
            label: "Promoted to Premier League",
          },
          "3-6": {
            bg: "bg-blue-900/40",
            border: "border-blue-500/60",
            icon: "🔄",
            label: "Playoffs for Promotion",
          },
          "22-24": {
            bg: "bg-red-900/40",
            border: "border-red-500/60",
            icon: "⬇️",
            label: "Relegated to League One",
          },
        },
      },
      {
        id: "league_one",
        name: "EFL League One",
        emoji: "🇬🇧",
        format: "league",
        teamCount: 24,
        rounds: 46,
        teams: [
          "AFC Wimbledon",
          "Barnsley",
          "Blackpool",
          "Bolton Wanderers",
          "Bradford City",
          "Burton Albion",
          "Cardiff City",
          "Doncaster Rovers",
          "Exeter City",
          "Huddersfield Town",
          "Leyton Orient",
          "Lincoln City",
          "Luton Town",
          "Mansfield Town",
          "Northampton Town",
          "Peterborough United",
          "Plymouth Argyle",
          "Port Vale",
          "Reading",
          "Rotherham United",
          "Stevenage",
          "Stockport County",
          "Wigan Athletic",
          "Wycombe Wanderers",
        ],
        positionStyles: {
          "1-2": {
            bg: "bg-yellow-900/40",
            border: "border-yellow-500/60",
            icon: "⬆️",
            label: "Promoted to Championship",
          },
          "3-6": {
            bg: "bg-blue-900/40",
            border: "border-blue-500/60",
            icon: "🔄",
            label: "Playoffs for Promotion",
          },
          "21-24": {
            bg: "bg-red-900/40",
            border: "border-red-500/60",
            icon: "⬇️",
            label: "Relegated to League Two",
          },
        },
      },
      {
        id: "league_two",
        name: "EFL League Two",
        emoji: "🇬🇧",
        format: "league",
        teamCount: 24,
        rounds: 46,
        teams: [
          "Accrington Stanley",
          "Barnet",
          "Barrow",
          "Bristol Rovers",
          "Bromley",
          "Cambridge United",
          "Cheltenham Town",
          "Chesterfield",
          "Colchester United",
          "Crewe Alexandra",
          "Fleetwood Town",
          "Gillingham",
          "Grimsby Town",
          "Harrogate Town",
          "Milton Keynes Dons",
          "Newport County",
          "Notts County",
          "Oldham Athletic",
          "Salford City",
          "Shrewsbury Town",
          "Swindon Town",
          "Tranmere Rovers",
          "Walsall",
          "Crawley Town",
        ],
        positionStyles: {
          "1-3": {
            bg: "bg-yellow-900/40",
            border: "border-yellow-500/60",
            icon: "⬆️",
            label: "Promoted to League One",
          },
          "4-7": {
            bg: "bg-blue-900/40",
            border: "border-blue-500/60",
            icon: "🔄",
            label: "Playoffs for Promotion",
          },
          "23-24": {
            bg: "bg-red-900/40",
            border: "border-red-500/60",
            icon: "⬇️",
            label: "Relegated to National League",
          },
        },
      },
      {
        id: "laliga",
        name: "La Liga",
        emoji: "🇪🇸",
        format: "league",
        teamCount: 20,
        rounds: 38,
        teams: [
          "Real Madrid",
          "Barcelona",
          "Atletico Madrid",
          "Athletic Bilbao",
          "Real Betis",
          "Real Sociedad",
          "Villarreal",
          "Valencia",
          "Sevilla",
          "Getafe",
          "Osasuna",
          "Girona",
          "Rayo Vallecano",
          "Las Palmas",
          "Alaves",
          "Celta Vigo",
          "Mallorca",
          "Espanyol",
          "Leganes",
          "Real Valladolid",
        ],
        positionStyles: {
          1: {
            bg: "bg-yellow-900/40",
            border: "border-yellow-500/60",
            icon: "🏆",
            label: "Champion",
          },
          "2-4": {
            bg: "bg-blue-900/40",
            border: "border-blue-500/60",
            icon: "🇪🇺",
            label: "Champions League",
          },
          5: {
            bg: "bg-orange-900/40",
            border: "border-orange-500/60",
            icon: "🟠",
            label: "Europa League",
          },
          6: {
            bg: "bg-green-900/40",
            border: "border-green-500/60",
            icon: "🟢",
            label: "Conference League",
          },
          "18-20": {
            bg: "bg-red-900/40",
            border: "border-red-500/60",
            icon: "⬇️",
            label: "Relegated",
          },
        },
      },
      {
        id: "champions",
        name: "Champions League",
        emoji: "🏆",
        format: "mixed",
        teamCount: 32,
        rounds: 6,
        playoffTeams: 16,
        groupCount: 8,
        teams: [
          "Arsenal",
          "Chelsea",
          "Liverpool",
          "Man City",
          "Man United",
          "Newcastle",
          "Tottenham",
          "Barcelona",
          "Real Madrid",
          "Atletico",
          "Girona",
          "Athletic Bilbao",
          "Bayern",
          "Bayer",
          "Dortmund",
          "Stuttgart",
          "PSG",
          "Marseille",
          "Monaco",
          "Napoli",
          "Inter",
          "AC Milan",
          "Juventus",
          "Atalanta",
          "Sporting",
          "Benfica",
          "PSV",
          "Feyenoord",
          "Ajax",
          "Galatasaray",
          "Celtic",
          "Shakhtar Donetsk",
        ],
        positionStyles: {
          "1-2": {
            bg: "bg-blue-900/40",
            border: "border-blue-500/60",
            icon: "⚡",
            label: "Qualified",
          },
          "3-4": {
            bg: "bg-red-900/40",
            border: "border-red-500/60",
            icon: "❌",
            label: "Eliminated",
          },
        },
      },
      {
        id: "bundesliga",
        name: "Bundesliga",
        emoji: "🇩🇪",
        format: "league",
        teamCount: 18,
        rounds: 34,
        teams: [
          "Bayern Munich",
          "Borussia Dortmund",
          "RB Leipzig",
          "Bayer Leverkusen",
          "Union Berlin",
          "SC Freiburg",
          "Eintracht Frankfurt",
          "VfL Wolfsburg",
          "FC Augsburg",
          "Borussia Monchengladbach",
          "VfB Stuttgart",
          "Werder Bremen",
          "TSG Hoffenheim",
          "FC Koln",
          "VfL Bochum",
          "Mainz 05",
          "SV Darmstadt",
          "FC Heidenheim",
        ],
        positionStyles: {
          1: {
            bg: "bg-yellow-900/40",
            border: "border-yellow-500/60",
            icon: "🏆",
            label: "Champion",
          },
          "2-4": {
            bg: "bg-blue-900/40",
            border: "border-blue-500/60",
            icon: "🇪🇺",
            label: "Champions League",
          },
          5: {
            bg: "bg-orange-900/40",
            border: "border-orange-500/60",
            icon: "🟠",
            label: "Europa League",
          },
          6: {
            bg: "bg-green-900/40",
            border: "border-green-500/60",
            icon: "🟢",
            label: "Conference League",
          },
          16: {
            bg: "bg-yellow-800/40",
            border: "border-yellow-600/60",
            icon: "🟡",
            label: "Relegation Playoff",
          },
          "17-18": {
            bg: "bg-red-900/40",
            border: "border-red-500/60",
            icon: "⬇️",
            label: "Relegated",
          },
        },
      },
      {
  id: "fa_cup",
  name: "FA Cup",
  emoji: "🏴",
  format: "knockout",
  teamCount: 64,
  playoffTeams: 64,
  teams: [
    "Arsenal",
    "Chelsea",
    "Liverpool",
    "Man City",
    "Man United",
    "Newcastle",
    "Tottenham",
    "Brighton",
    "Aston Villa",
    "West Ham",
    "Crystal Palace",
    "Fulham",
    "Brentford",
    "Wolves",
    "Everton",
    "Southampton",
    "Leicester City",
    "Leeds United",
    "Nottingham Forest",
    "Burnley",
    "Watford",
    "Norwich City",
    "Bournemouth",
    "Sheffield United",
    "Middlesbrough",
    "Blackburn Rovers",
    "Sunderland",
    "West Bromwich Albion",
    "Stoke City",
    "Swansea City",
    "Cardiff City",
    "Bristol City",
    "Preston North End",
    "Millwall",
    "Coventry City",
    "Hull City",
    "Birmingham City",
    "Plymouth Argyle",
    "Ipswich Town",
    "Portsmouth",
    "Derby County",
    "Bolton Wanderers",
    "Sheffield Wednesday",
    "Charlton Athletic",
    "Reading",
    "Oxford United",
    "Shrewsbury Town",
    "Burton Albion",
    "Lincoln City",
    "Port Vale",
    "Fleetwood Town",
    "Accrington Stanley",
    "Cambridge United",
    "Cheltenham Town",
    "Exeter City",
    "Bristol Rovers",
    "Peterborough United",
    "Wycombe Wanderers",
    "Barnsley",
    "Wigan Athletic",
    "Blackpool",
    "Luton Town",
    "Rotherham United",
    "Oldham Athletic"
  ],
  positionStyles: {
    all: {
      bg: "bg-gray-800/40",
      border: "border-gray-700/60",
      icon: "⚪",
      label: "In Tournament",
    },
  },
},
      {
        id: "ekstraklasa_league",
        name: "Ekstraklasa League",
        emoji: "🇵🇱",
        format: "league",
        teamCount: 18,
        rounds: 34,
        teams: [
          "Arka Gdynia",
          "Bruk-Bet",
          "Cracovia",
          "GKS Katowice",
          "Górnik Zabrze",
          "Jagiellonia Białystok",
          "Korona Kielce",
          "Lech Poznań",
          "Lechia Gdańsk",
          "Legia Warsaw",
          "Motor Lublin",
          "Piast Gliwice",
          "Pogoń Szczecin",
          "Radomiak Radom",
          "Raków Częstochowa",
          "Widzew Łódź",
          "Wisła Płock",
          "Zagłębie Lubin",
        ],
        positionStyles: {
          1: {
            bg: "bg-yellow-900/40",
            border: "border-yellow-500/60",
            icon: "🏆",
            label: "Champion",
          },
          2: {
            bg: "bg-blue-900/40",
            border: "border-blue-500/60",
            icon: "🇪🇺",
            label: "Champions League",
          },
          3: {
            bg: "bg-orange-900/40",
            border: "border-orange-500/60",
            icon: "🟠",
            label: "Europa League",
          },
          4: {
            bg: "bg-green-900/40",
            border: "border-green-500/60",
            icon: "🟢",
            label: "Conference League",
          },
          "16-18": {
            bg: "bg-red-900/40",
            border: "border-red-500/60",
            icon: "⬇️",
            label: "Relegated",
          },
        },
      },

      {
        id: "snakedeer_league",
        name: "Snake Deer Ekstraklasa League",
        emoji: "🇵🇱",
        format: "league",
        teamCount: 20,
        rounds: 38,
        teams: [
          "Cat FC",
          "Cat Cathedral FC",
          "North river",
          "Stie cathedral",
          "Elizibeth FC",
          "Buck FC",
          "Lowska FC",
          "Kryński FC",
          "FC lionskz",
          "Morensz FC",
          "Łorenski FC",
          "Fort oleski FC",
          "FC waszski",
          "Mountenysk",
          "Saresko",
          "Rawskiego FC",
          "Interszk FC",
          "Lwowski FC",
          "Stront FC",
          "Arsenów",
        ],
        positionStyles: {
          1: {
            bg: "bg-yellow-900/40",
            border: "border-yellow-500/60",
            icon: "🏆",
            label: "Champion",
          },
          "2-4": {
            bg: "bg-blue-900/40",
            border: "border-blue-500/60",
            icon: "🇪🇺",
            label: "Club Great League",
          },
          "5-6": {
            bg: "bg-orange-900/40",
            border: "border-orange-500/60",
            icon: "🟠",
            label: "Club Vents League",
          },
          "7-8": {
            bg: "bg-green-900/40",
            border: "border-green-500/60",
            icon: "🟢",
            label: "Club Vents League Qualifier",
          },
          "18-20": {
            bg: "bg-red-900/40",
            border: "border-red-500/60",
            icon: "⬇️",
            label: "Relegated",
          },
        },
      }
        ];