export const COMPETITIONS = [
  {
    id: "premier",
    name: "Premier League",
    emoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    format: "league",
    teamCount: 20,
    rounds: 38,
    teams: [
      "Arsenal",
      "Aston Villa",
      "Bournemouth",
      "Brentford",
      "Brighton",
      "Burnley",
      "Chelsea",
      "Crystal Palace",
      "Everton",
      "Fulham",
      "Leeds",
      "Liverpool",
      "City",
      "United",
      "Newcastle",
      "Forest",
      "Sunderland",
      "Tottenham",
      "West Ham",
      "Wolves"
    ], // based on 2025-26 list. :contentReference[oaicite:0]{index=0}
    positionStyles: {
      1: { bg: "bg-yellow-900/40", border: "border-yellow-500/60", icon: "🏆", label: "Champion" },
      "2-5": { bg: "bg-blue-900/40", border: "border-blue-500/60", icon: "🇪🇺", label: "Champions League" },
      6: { bg: "bg-orange-900/40", border: "border-orange-500/60", icon: "🇪🇺", label: "Europa League" },
      7: { bg: "bg-green-900/40", border: "border-green-500/60", icon: "🇪🇺", label: "Conference League" },
      "18-20": { bg: "bg-red-900/40", border: "border-red-500/60", icon: "⬇️", label: "Relegated" },
    },
  },
  {
    id: "scottish",
    name: "Scottish Premiership",
    emoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    format: "league",
    teamCount: 12,
    rounds: 22,
    teams: [
      "Aberdeen",
      "Celtic",
      "Dundee",
      "Dundee Utd",
      "Hearts",
      "Hibernian",
      "Kilmarnock",
      "Livingston",
      "Motherwell",
      "Rangers",
      "Ross County",
      "St Mirren"
    ],
    positionStyles: {
      1: { bg: "bg-yellow-900/40", border: "border-yellow-500/60", icon: "🏆", label: "Champion" },
      2: { bg: "bg-blue-900/40", border: "border-blue-500/60", icon: "🇪🇺", label: "Champions League Qual." },
      "3-4": { bg: "bg-orange-900/40", border: "border-orange-500/60", icon: "🇪🇺", label: "Europa/Conference League" },
      11: { bg: "bg-red-900/40", border: "border-red-500/60", icon: "🔄", label: "Playoff (Relegation)" },
      12: { bg: "bg-red-900/40", border: "border-red-500/60", icon: "⬇️", label: "Relegated" },
    },
  },
  {
    id: "championship",
    name: "EFL Championship",
    emoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    format: "league",
    teamCount: 24,
    rounds: 46,
    teams: [
      "Birmingham",
      "Blackburn",
      "Bristol City",
      "Charlton",
      "Coventry",
      "Derby",
      "Hull",
      "Ipswich",
      "Leicester",
      "Middlesbrough",
      "Millwall",
      "Norwich",
      "Oxford Utd",
      "Portsmouth",
      "Preston",
      "QPR",
      "Sheff Utd",
      "Sheff Wed",
      "Southampton",
      "Stoke",
      "Swansea",
      "Watford",
      "West Brom",
      "Wrexham"
    ], // promotion/relegation updates noted. :contentReference[oaicite:1]{index=1}
    positionStyles: {
      "1-2": { bg: "bg-yellow-900/40", border: "border-yellow-500/60", icon: "⬆️", label: "Promoted to Premier" },
      "3-6": { bg: "bg-blue-900/40", border: "border-blue-500/60", icon: "🔄", label: "Playoffs for Promotion" },
      "22-24": { bg: "bg-red-900/40", border: "border-red-500/60", icon: "⬇️", label: "Relegated to League One" },
    },
  },
  {
    id: "league_one",
    name: "EFL League One",
    emoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    format: "league",
    teamCount: 24,
    rounds: 46,
    teams: [
      "AFC Wimbledon",
      "Barnsley",
      "Blackpool",
      "Bolton",
      "Bradford",
      "Burton",
      "Cardiff",
      "Doncaster",
      "Exeter",
      "Huddersfield",
      "Leyton Orient",
      "Lincoln",
      "Luton",
      "Mansfield",
      "Northampton",
      "Peterborough",
      "Plymouth",
      "Port Vale",
      "Reading",
      "Rotherham",
      "Stevenage",
      "Stockport",
      "Wigan",
      "Wycombe"
    ], // verified list forthcoming. :contentReference[oaicite:2]{index=2}
    positionStyles: {
      "1-2": { bg: "bg-yellow-900/40", border: "border-yellow-500/60", icon: "⬆️", label: "Promoted to Championship" },
      "3-6": { bg: "bg-blue-900/40", border: "border-blue-500/60", icon: "🔄", label: "Playoffs for Promotion" },
      "21-24": { bg: "bg-red-900/40", border: "border-red-500/60", icon: "⬇️", label: "Relegated to League Two" },
    },
  },
  {
    id: "laliga",
    name: "La Liga",
    emoji: "🇪🇸",
    format: "league",
    teamCount: 20,
    rounds: 38,
    teams: [
      "Real Madrid",
      "Barcelona",
      "Atletico Madrid",
      "Athletic Bilbao",
      "Real Betis",
      "Real Sociedad",
      "Villarreal",
      "Valencia",
      "Sevilla",
      "Getafe",
      "Osasuna",
      "Girona",
      "Rayo Vallecano",
      "Las Palmas",
      "Alaves",
      "Celta Vigo",
      "Mallorca",
      "Espanyol",
      "Leganes",
      "Real Valladolid"
    ], // as per your original list (no changes sourced)
    positionStyles: {
      1: { bg: "bg-yellow-900/40", border: "border-yellow-500/60", icon: "🏆", label: "Champion" },
      "2-4": { bg: "bg-blue-900/40", border: "border-blue-500/60", icon: "🇪🇺", label: "Champions League" },
      5: { bg: "bg-orange-900/40", border: "border-orange-500/60", icon: "🟠", label: "Europa League" },
      6: { bg: "bg-green-900/40", border: "border-green-500/60", icon: "🟢", label: "Conference League" },
      "18-20": { bg: "bg-red-900/40", border: "border-red-500/60", icon: "⬇️", label: "Relegated" },
    },
  },
  {
    id: "champions",
    name: "Champions League",
    emoji: "🇪🇺",
    format: "mixed",
    teamCount: 32,
    rounds: 6,
    playoffTeams: 16,
    groupCount: 8,
    teams: [
      "Arsenal",
      "Chelsea",
      "Liverpool",
      "City",
      "United",
      "Newcastle",
      "Tottenham",
      "Barcelona",
      "Real Madrid",
      "Atletico Madrid",
      "Girona",
      "Athletic Bilbao",
      "Bayern Munich",
      "Bayer Leverkusen",
      "Dortmund",
      "Stuttgart",
      "PSG",
      "Marseille",
      "Monaco",
      "Napoli",
      "Inter Milan",
      "AC Milan",
      "Juventus",
      "Atalanta",
      "Sporting CP",
      "Benfica",
      "PSV",
      "Feyenoord",
      "Ajax",
      "Galatasaray",
      "Celtic",
      "Shakhtar Donetsk"
    ],
    positionStyles: {
      "1-2": { bg: "bg-blue-900/40", border: "border-blue-500/60", icon: "⚡", label: "Qualified" },
      "3-4": { bg: "bg-red-900/40", border: "border-red-500/60", icon: "❌", label: "Eliminated" },
    },
  },
  {
    id: "bundesliga",
    name: "Bundesliga",
    emoji: "🇩🇪",
    format: "league",
    teamCount: 18,
    rounds: 34,
    teams: [
      "Bayern Munich",
      "Dortmund",
      "RB Leipzig",
      "Bayer Leverkusen",
      "Union Berlin",
      "Freiburg",
      "Frankfurt",
      "Wolfsburg",
      "Augsburg",
      "Monchengladbach",
      "Stuttgart",
      "Werder Bremen",
      "Hoffenheim",
      "Koln",
      "Bochum",
      "Mainz",
      "Darmstadt",
      "Heidenheim"
    ],
    positionStyles: {
      1: { bg: "bg-yellow-900/40", border: "border-yellow-500/60", icon: "🏆", label: "Champion" },
      "2-4": { bg: "bg-blue-900/40", border: "border-blue-500/60", icon: "🇪🇺", label: "Champions League" },
      5: { bg: "bg-orange-900/40", border: "border-orange-500/60", icon: "🟠", label: "Europa League" },
      6: { bg: "bg-green-900/40", border: "border-green-500/60", icon: "🟢", label: "Conference League" },
      16: { bg: "bg-yellow-800/40", border: "border-yellow-600/60", icon: "🟡", label: "Relegation Playoff" },
      "17-18": { bg: "bg-red-900/40", border: "border-red-500/60", icon: "⬇️", label: "Relegated" },
    },
  },
  {
    id: "fa_cup",
    name: "FA Cup",
    emoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    format: "knockout",
    teamCount: 64,
    playoffTeams: 64,
    teams: [
      "Arsenal",
      "Chelsea",
      "Liverpool",
      "City",
      "United",
      "Newcastle",
      "Tottenham",
      "Brighton",
      "Aston Villa",
      "West Ham",
      "Crystal Palace",
      "Fulham",
      "Brentford",
      "Wolves",
      "Everton",
      "Southampton",
      "Leicester",
      "Leeds",
      "Nottingham Forest",
      "Burnley",
      "Watford",
      "Norwich",
      "Bournemouth",
      "Sheff Utd",
      "Middlesbrough",
      "Blackburn",
      "Sunderland",
      "West Brom",
      "Stoke",
      "Swansea",
      "Cardiff",
      "Bristol City",
      "Preston",
      "Millwall",
      "Coventry",
      "Hull",
      "Birmingham",
      "Plymouth",
      "Ipswich",
      "Portsmouth",
      "Derby",
      "Bolton",
      "Sheff Wed",
      "Charlton",
      "Reading",
      "Oxford Utd",
      "Shrewsbury",
      "Burton",
      "Lincoln",
      "Port Vale",
      "Fleetwood",
      "Accrington",
      "Cambridge",
      "Cheltenham",
      "Exeter",
      "Bristol Rovers",
      "Peterborough",
      "Wycombe",
      "Barnsley",
      "Wigan",
      "Blackpool",
      "Luton",
      "Rotherham",
      "Oldham"
    ],
    positionStyles: {
      all: { bg: "bg-gray-800/40", border: "border-gray-700/60", icon: "⚪", label: "In Tournament" },
    },
  },
  {
    id: "ekstraklasa_league",
    name: "Ekstraklasa League",
    emoji: "🇵🇱",
    format: "league",
    teamCount: 18,
    rounds: 34,
    teams: [
      "Arka Gdynia",
      "Bruk-Bet",
      "Cracovia",
      "GKS Katowice",
      "Gornik Zabrze",
      "Jagiellonia",
      "Korona Kielce",
      "Lech Poznan",
      "Lechia Gdansk",
      "Legia Warsaw",
      "Motor Lublin",
      "Piast Gliwice",
      "Pogon Szczecin",
      "Radomiak Radom",
      "Rakow Częstochowa",
      "Widzew Lodz",
      "Wisla Plock",
      "Zaglebie Lubin"
    ],
    positionStyles: {
      1: { bg: "bg-yellow-900/40", border: "border-yellow-500/60", icon: "🏆", label: "Champion" },
      2: { bg: "bg-blue-900/40", border: "border-blue-500/60", icon: "🇪🇺", label: "Champions League" },
      3: { bg: "bg-orange-900/40", border: "border-orange-500/60", icon: "🟠", label: "Europa League" },
      4: { bg: "bg-green-900/40", border: "border-green-500/60", icon: "🟢", label: "Conference League" },
      "16-18": { bg: "bg-red-900/40", border: "border-red-500/60", icon: "⬇️", label: "Relegated" },
    },
  },
];